module.exports.Commands = process.env.COMMAND_VERSION =="FAKE" ? 

{
    Start : /NosStart/,
    Init : /no init/,
    Version :/no Version/,
    Help : /no Help/,
    AddIcs : /no IcsAdd /,
    RemoveIcs : /no IcsRemove /,
    AllMangiamo : /NOT-MangiareAll/,
    AddMangiamo : /NOT-MangiareAdd /,
    RemoveMangiamo : /NOT-MangiareRemove /,
    AllBartek : /no BartekAll/,
    AddBartek : /no BartekAdd /,
    RemoveBartek: /no BarteKRemove /,
    Ics : /no ics/,
    IcsAll : /NOIcsAll/,
    Bartek : /no Domandati/,
    Mangiamo : /no Mangiamo/,
    QuelloDiceCose: /no QuelloDiceCose/,
    AllQuelloDiceCose: /no RDiceAll/,
    AddQuelloDiceCose: /no RDiceAdd /,
    RemoveQuelloDiceCose: /no RDiceRemove /,
    Dio: /DiOpork/
   } :
   {
    Start : /Start/,
    Init : /init/,
    Version :/Version/,
    Help : /Help/,
    AddIcs : /IcsAdd /,
    RemoveIcs : /IcsRemove /,
    AllMangiamo : /NOT-MangiareAll/,
    AddMangiamo : /NOT-MangiareAdd /,
    RemoveMangiamo : /NOT-MangiareRemove /,
    AllBartek : /BartekAll/,
    AddBartek : /BartekAdd /,
    RemoveBartek: /BarteKRemove /,
    Ics : /ics/,
    IcsAll : /IcsAll/,
    Bartek : /Domandati/,
    Mangiamo : /Mangiamo/,
    QuelloDiceCose: /QuelloDiceCose/,
    AllQuelloDiceCose: /RDiceAll/,
    AddQuelloDiceCose: /RDiceAdd /,
    RemoveQuelloDiceCose: /RDiceRemove /,
    Dio: /Dio/
   };